version: '3'
services:
  # Frontend Angular app
  angular-frontend:
    build:
      context: ./angular-frontend
    ports:
      - '4200:80'
    depends_on:
      - node-backend

  # Backend Node.js app
  node-backend:
    build:
      context: ./node-backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

